### PR TITLE
52 organize backend

### PR DESCRIPTION
**Pull request by chphoom**
main goal of organizing backend api's via tagging was accomplished, some of them don't have full comments or documentations but tags are enough for now.

### CODE REVIEW

**Comment by chphoom** [comment]
current TODO: add unit tests

**Comment by chphoom** [comment]
merged with new stuff from recent PR, lets make sure new features still work

**Comment by chphoom** [comment]
ready to be merged

**Review by elaine331917 — APPROVED** [review]
LGTM

**Pull request merged**
