### PR TITLE
enhance post display and privacy

### PR DESCRIPTION
**Pull request by elaine331917**
this PR addresses #153 and #139 and #157 

- post display on home page, mechallenge, and search have been updated. i ran into an infinite loop trying to get the post display name and pfp so i decided Not to do that
- private posts and private account pages now display "private" instead when another user tries to access them

### CODE REVIEW

**Comment by chphoom** [comment]
i can fix the infinite loop, will address at a later time

**Comment by elaine331917** [comment]
i tried it with multiple methods including
- calling the get user service directly in the html: <div class="thumbnail-user" *ngIf="user_serv.getUser(post.user_id) | async as user">{{user.displayName}}</div>
- making a new function in registration-service to get the user from the post's user_id (basically the same thing as the first)

**Review by chphoom — CHANGES_REQUESTED** [review]
in the home component there is instruction of what code to add to other pages to circumnavigate the infinite loop in .ts file and in the html file there is an example of how to get or display that info. i don't know how to style what u wanted to so i will hand this back to you to adjust the styling on the home page and add the functionality to the other pages u worked on!

**Review by chphoom — APPROVED** [review]
lets get this bread

**Pull request merged**
