### PR TITLE
134 additional dev data

### PR DESCRIPTION
**Pull request by elaine331917**
### Major changes:
- dev data updated
- comments display name is clickable
- login/signup, upload post, and update profile forms now have field error messages
- upload posts now requires url field to be not empty and sets title to "Untitled" if no title is entered
- automatically add the we or mechallenge tag to posts
- change the color of the prompt based on we or me in posts and uploads (changing it in your saved challenges would require the challenge interface to have the attribute "type" but it does not)

this pr is me doing everything to procrastinate on implementing editing posts

### CODE REVIEW

**Comment by chphoom** [comment]
i will check this first thing in the morning (11:30am at the latest)

**Comment by chphoom** [comment]
> i will check this first thing in the morning (11:30am at the latest)

oh my god elaine u really went off huh

**Comment by elaine331917** [comment]
> > i will check this first thing in the morning (11:30am at the latest)
> 
> oh my god elaine u really went off huh

i need to get rid of all these issues 😫

**Review by chphoom — CHANGES_REQUESTED** [review]
i made u a getType function in the profile component os u can do the color thing there <3

**Comment by elaine331917** [comment]
image

**Review by chphoom — APPROVED** [review]
image

**Pull request merged**
